project:
    execute-dir: project
    output-dir: bin

author: "Romain Ferrali"

editor:
    render-on-save: false

format:
    pdf:
        fig-width: 6.2
        lof: true
        lot: true
        number-sections: true
        geometry:
            - top=1in
            - bottom=1in
            - left=1in
            - right=1in

knitr:
    opts_chunk:
        echo: false
        R.options:
            knitr.kable.NA: ""
            dplyr.summarise.inform: false
